config/routes.rb
Rails.application.routes.draw do
  root 'signup#index'
  resources :newsletter, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController
  def new
  end

  def create
    NewsletterJob.perform_later({
      emails: params[:emails],
      subject: params[:subject],
      newsletter: params[:newsletter]
      })
    flash[:success] = 'Newsletter Sent!'
    redirect_to new_newsletter_path
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailingListProject and Job Thing Example</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
    <div class="flash <%= value %>">
      <%= value %>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/newsletter/monthly.html.haml
%h1= class_name + "#" + @action

%p
  = @greeting + ", find me in app/views/newsletter/monthly.html.haml"

app/views/newsletter/monthly.text.haml
Newsletter#monthly

= @greeting + ", find me in app/views/newsletter/monthly.text.haml"

app/views/newsletter/new.html.erb
<h3>Send A Newsletter</h3>
<hr />


<%= form_tag newsletter_index_path do %>
  <div>
    <%= label_tag "Subject" %>
    <br />
    <%= text_area_tag "subject", nil, placeholder: 'Subject', cols: '20', rows: '5', required: true %>
  </div>

  <div>
      <%= label_tag "Emails (*comma separated)" %>
      <br />
      <%= text_area_tag "emails", nil, placeholder: 'test@test.com, contact@dpl.com', required: true, cols: '20', rows: '5' %>
    </div>
  <hr />
  <div>
    <%= label_tag "Newsletter Type" %>
    <br />
      <%= select_tag "newsletter", options_for_select(['weekly', 'monthly', 'yearly']) %>
    </div>
    <hr />
    <%= submit_tag "Send" %>
<% end %>

app/views/newsletter/weekly.html.haml
%h1= class_name + "#" + @action

%p
  = @greeting + ", find me in app/views/newsletter/weekly.html.haml"

app/views/newsletter/weekly.text.haml
Newsletter#weekly

= @greeting + ", find me in app/views/newsletter/weekly.text.haml"

app/views/newsletter/yearly.html.haml
%h1= class_name + "#" + @action

%p
  = @greeting + ", find me in app/views/newsletter/yearly.html.haml"

app/views/newsletter/yearly.text.haml
Newsletter#yearly

= @greeting + ", find me in app/views/newsletter/yearly.text.haml"

app/views/signup/index.html.haml
%h1 Signup#index
%p Find me in app/views/signup/index.html.haml